### PR TITLE
ci(rust.yml/jobs/clippy): integrate with GitHub Code Scanning

### PR DESCRIPTION
**Pull request by DataM0del**
## Description

See CCBlueX/LiquidBounce#4887, it's basically this but for detekt (because that's what LiquidBounce uses for linting their Kotlin part).

This PR pretty much just adds more QoL. Nothing really useful for anyone who isn't reviewing the code for PRs.
See https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning#about-third-party-code-scanning-tools
Also, you can probably open up the results.sarif file in any JetBrains IDE (e.g. IntelliJ IDEA) with Server-side Analysis and see all linting errors.

## Testing

- [x] See if CI passes
- [x] After CI passes, intentionally make clippy trigger a warning
- [x] Observe the results and see if it works

## Checklist
Things need to be done before this Pull Request can be merged.

- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
<!--
- [x] All unit tests pass: `cargo test`
- [x] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)
--!>

### CODE REVIEW

**Comment by DataM0del** [comment]
I forgot it to install clippy-sarif in the release mode linting job :skull:

**Comment by DataM0del** [comment]
Now let's trigger clippy.

**Comment by DataM0del** [comment]
Now let's revert it!

**Comment by DataM0del** [comment]
image

**Comment by DataM0del** [comment]
It says fixed now.

**Comment by Snowiiii** [comment]
So, What does this do ?

**Comment by DataM0del** [comment]
> So, What does this do ?

It adds a "review" that comments on each line that clippy screams at, instead of you having to go look at the CI logs for the clippy job.

**Comment by Snowiiii** [comment]
I don't think this is really needed, I think its more annoying that actually useful. People also don't really have to go into the CI logs. They can just see what CI failed and then fix it locally

**Pull request closed without merging**
