### PR TITLE
Add Pick item (Middle Mouse Click)

### PR DESCRIPTION
**Pull request by Bafran**
## Description

Issue #397 

Adding Pick Item (Middle Mouse Click). In survival, searches inventory and brings the item to the appropriate hotbar slot if available. In creative, sets the hotbar slot or grabs the item as appropriate.

Todo is adding pick item from entity. A placeholder was left however I don't believe /spawn and spawn eggs are implemented so I didn't have a way of testing on mobs and left that work as a todo.

## Testing
- Verified middle mouse click picks item in survival mode
- Verified middle mouse click picks item in creative mode
- Verified that middle mouse click in creative gives player item if item is not already in inventory
- Verified that middle mouse click in creative gives deletes an item from inventory if inventory is full

## Checklist
Things need to be done before this Pull Request can be merged.
- [x] Code is well-formatted and adheres to project style guidelines: `cargo fmt`
- [x] Code does not produce any clippy warnings: `cargo clippy`
- [x] All unit tests pass: `cargo test`
- [ ] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

## Documentation
I literally could not get the actual docs to load so these are links to internet archive

[Pick Item](https://web.archive.org/web/20241130183642/http://wiki.vg/Protocol#Click_Container:~:text=button%20is%20held.-,Pick%20Item,-Used%20to%20swap)
[Set Creative Mode Slot](https://web.archive.org/web/20241130183642/http://wiki.vg/Protocol#Set_Creative_Mode_Slot:~:text=the%20command%20block.-,Set%20Creative%20Mode%20Slot,-While%20the%20user)

### CODE REVIEW

**Comment by Bafran** [comment]
Current progress - general structure is in place but crashes upon middle mouse click because the item stack comes back as none

**Comment by Snowiiii** [comment]
Hey, Thanks for your interest in Contributing @Bafran :D. Looks good so far. @Bryntet likes to review Inventory stuff, But sometimes he needs a while

**Comment by Snowiiii** [comment]
After testing i noticed that when you pick a block you already have in your hotbar you get another one, This is not vanilla behaviour. You should check if the player already has the block in this hotbar and when yes just switch to it

**Comment by Snowiiii** [comment]
Now everything works great. Big thanks @Bafran for your great work. Keep it up :wink:

**Pull request merged**
